### PR TITLE
fix: do not include docs/conf.py & scripts in wheel

### PR DESCRIPTION
**Pull request by mgorny**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-auth-library-python-oauthlib/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by clundin25** [comment]
@mgorny Thank you for this change. The contents look correct. It seems the lint check is failing, so please run `nox -s blacken` to fix the formatting issues, and push those changes.

**Comment by parthea** [comment]
adding @dandhlee as reviewer for the docs pipeline

**Comment by mgorny** [comment]
Sorry about that, should be fixed now.

**Review by clundin25 — APPROVED** [review]

**Comment by dandhlee** [comment]
Fine to exclude`docs` directory for setup, any reason why it's marked as a `fix`? Have you run into any issues?

**Comment by mgorny** [comment]
Yes. Since the files are included in wheels, they are installed inside `site-packages`. This triggers QA checks in Gentoo and causes the build process to error out due to installing forbidden/collision-prone top-level packages.

**Comment by dandhlee** [comment]
Just curious, where/how are you seeing them in `site-packages`?

Could you elaborate a bit more on how your tool is installing the top level packages?

This also sounds like it's a problem unique to the tool, so I'd mark it as a `chore` or `build` prefix rather than `fix`, unless this is fixing a bug directly related to this repository content.

**Comment by mgorny** [comment]
To reproduce:

```
git clone https://github.com/googleapis/google-auth-library-python-oauthlib/
cd google-auth-library-python-oauthlib
python -m venv .venv
. .venv/bin/activate
pip install .
ls .venv/lib/python3.12/site-packages/
```

You're going to notice that there are `docs` and `scripts` directories there.

**Comment by mgorny** [comment]
Ping.

**Comment by mgorny** [comment]
Thank you!

**Pull request merged**
